# Changes here will be overwritten by Copier
_commit: 536d823
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: true
copyright_year: '2024'
django_app_shorthand: qr
documentation: true
email: abe@habet.dev
full_name: Abe Hanoka
github_username: abe-101
has_cli: false
initial_commit: true
is_django_package: true
open_source_license: MIT
package_name: django_qr
project_name: Django QR
project_short_description: Generate and manage QR codes that redirect to specific
    views in your Django project
project_slug: django-qr
run_poetry_install: true
setup_github: true
setup_pre_commit: true

